ALTER TABLE public.price_configs
  ADD COLUMN IF NOT EXISTS yp_one_way_fee numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_round_trip_fee numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_threshold_1 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_discount_ow_1 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_discount_rt_1 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_threshold_2 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_discount_ow_2 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_discount_rt_2 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_threshold_3 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_discount_ow_3 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_discount_rt_3 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_threshold_4 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_discount_ow_4 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_discount_rt_4 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_threshold_5 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_discount_ow_5 numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS yp_discount_rt_5 numeric NOT NULL DEFAULT 0;
